#!/usr/bin/env node

import { readFileSync } from "node:fs";
import { basename, dirname, extname, join } from "node:path";
import walkSync from "walk-sync";

const MIME_TYPES: Record<string, string> = {
  ".css": "text/css",
  ".gif": "image/gif",
  ".gz": "application/gzip",
  ".htm": "text/html",
  ".html": "text/html",
  ".ico": "image/vnd.microsoft.icon",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".js": "text/javascript",
  ".json": "application/json",
  ".map": "application/json",
  ".mp4": "video/mp4",
  ".otf": "font/otf",
  ".png": "image/png",
  ".ts": "text/typescript",
  ".ttf": "font/ttf",
  ".txt": "text/plain",
  ".wav": "audio/wav",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".zip": "application/zip",
};

export function staticFileBundle(
  root: string,
  options: { include?: string[]; exclude?: string[] } = {},
): string {
  const setup: string[] = [];
  const entries: string[] = [];
  let next = 0;
  function nextVarname() {
    return `_${next++}`;
  }
  const paths = walkSync(root, {
    directories: false,
    globs: options.include,
    ignore: options.exclude,
  });
  for (const p of paths) {
    const name = basename(p);
    const varname = nextVarname();
    const ext = extname(name);
    const dir = dirname(join("/", p));
    const key = JSON.stringify(join(dir, name));
    const type = MIME_TYPES[ext] ?? "application/octet-stream";
    if (name === "index.html") {
      const text = readFileSync(join(root, p), "utf-8");
      setup.push(`const ${varname} = ${JSON.stringify(text)};`);
      const index = JSON.stringify(join(dir, "/"));
      if (dir !== "/") {
        entries.push(
          `${JSON.stringify(dir)}: () => new Response(null, { status: 308, headers: { Location: ${index} }}),`,
        );
      }
      entries.push(
        `${index}: () => new Response(${varname}, { headers: { "Content-Type": "${type}" } }),`,
      );
    } else if (type.startsWith("text/")) {
      const text = readFileSync(join(root, p), "utf-8");
      setup.push(`const ${varname} = ${JSON.stringify(text)};`);
      entries.push(
        `${key}: () => new Response(${varname}, { headers: { "Content-Type": "${type}" } },),`,
      );
    } else {
      const data = readFileSync(join(root, p));
      const base64 = Buffer.from(data).toString("base64");
      setup.push(`const ${varname} = atob("${base64}");`);
      entries.push(
        `${key}: () => new Response(${varname}, { headers: { "Content-Type": "${type}" } }),`,
      );
    }
  }
  return [
    "// Auto-generated by static-file-bundle.ts",
    "",
    ...setup,
    "",
    "const manifest: Record<string, () => Response> = {",
    ...entries.map((e) => `  ${e}`),
    "};",
    "",
    "export default function handle(request: Request): Response | undefined {",
    "  const url = new URL(request.url);",
    "  return manifest[url.pathname]?.();",
    "}",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const dir = process.argv[2];
  if (!dir) {
    console.error("Usage: static-file-bundle <directory>");
    process.exit(1);
  }
  process.stdout.write(staticFileBundle(dir));
}
