import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { collectSecrets, secretsToEnv } from "./secrets.ts";
import { taskRoots } from "./taskRoots.ts";
import {
  loadTurboGraph,
  type TurboGraph,
  transitiveDependencies,
} from "./turboGraph.ts";
import type { PackageInfo, WorkflowContext, WorkieConfig } from "./types.ts";
import { validateWorkflow } from "./validateWorkflow.ts";
import { yaml } from "./yaml.ts";

const PREFIX = "workie-";
const WORKFLOWS_DIR = ".github/workflows";
const HEADER = "# Auto-generated by workie -- do not edit manually.";

export type GenerateOptions = {
  /** Monorepo root. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Print a summary to stdout. Defaults to `true`. */
  log?: boolean;
  /**
   * Pre-computed turbo graph. If omitted, `generate` invokes `loadTurboGraph`
   * in `cwd`. Useful for tests.
   */
  graph?: TurboGraph;
};

export type GenerateResult = {
  /** Workflow filenames written or overwritten in this run. */
  written: string[];
  /** Workflow filenames that were up-to-date and left alone. */
  unchanged: string[];
  /** Stale `workie-*` workflow files deleted in this run. */
  removed: string[];
};

export async function generate(
  config: WorkieConfig,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  const cwd = options.cwd ?? process.cwd();
  const log = options.log ?? true;
  const absDir = join(cwd, WORKFLOWS_DIR);

  if (!existsSync(absDir) || !statSync(absDir).isDirectory()) {
    throw new Error(
      `workie: workflows directory not found: ${WORKFLOWS_DIR}\n` +
        `Create it first so workie knows it's writing to the right place.`,
    );
  }

  const graph = options.graph ?? loadTurboGraph(cwd);

  const written: string[] = [];
  const unchanged: string[] = [];
  const generated = new Map<string, string>();
  const errors: string[] = [];

  const allTasks = Object.keys(config.tasks);
  for (const [task, fn] of Object.entries(config.tasks)) {
    const otherTasks = allTasks.filter((t) => t !== task);
    const roots = taskRoots(graph, task, { otherTasks });
    for (const root of roots) {
      const deps = transitiveDependencies(graph, root.name);
      const dependencies = [...deps]
        .map((n) => graph.byName.get(n))
        .filter((p): p is PackageInfo => p !== undefined);
      const paths = dependencies
        .map((p) => p.path)
        .filter((p) => p !== "")
        .map((p) => `${p}/**`)
        .sort();
      const env = secretsToEnv(collectSecrets(graph, root, task));
      const ctx: WorkflowContext = {
        task,
        pkg: root,
        paths,
        dependencies,
        env,
      };
      const workflow = fn(ctx);
      if (!workflow) {
        continue;
      }

      const result = validateWorkflow(workflow);
      if (!result.ok) {
        errors.push(
          `Task "${task}" for package "${root.name}" produced an invalid workflow:\n  ` +
            result.errors.join("\n  "),
        );
        continue;
      }

      const filename = workflowFilename(task, root);
      if (generated.has(filename)) {
        errors.push(
          `Two workflows claimed the same filename: ${filename}. ` +
            `Check your task templates -- each (task, package) pair must produce a unique filename.`,
        );
        continue;
      }
      generated.set(filename, `${HEADER}\n\n${yaml(workflow)}`);
    }
  }

  if (errors.length > 0) {
    throw new Error(`workie: ${errors.length} error(s)\n${errors.join("\n")}`);
  }

  mkdirSync(absDir, { recursive: true });

  for (const [filename, body] of generated) {
    const filepath = join(absDir, filename);
    if (existsSync(filepath) && readFileSync(filepath, "utf-8") === body) {
      unchanged.push(filename);
      continue;
    }
    writeFileSync(filepath, body);
    written.push(filename);
    if (log) {
      console.log(`  wrote ${join(WORKFLOWS_DIR, filename)}`);
    }
  }

  const removed: string[] = [];
  for (const entry of readdirSync(absDir)) {
    if (!entry.startsWith(PREFIX)) {
      continue;
    }
    if (!entry.endsWith(".yml") && !entry.endsWith(".yaml")) {
      continue;
    }
    if (generated.has(entry)) {
      continue;
    }
    unlinkSync(join(absDir, entry));
    removed.push(entry);
    if (log) {
      console.log(`  removed stale ${join(WORKFLOWS_DIR, entry)}`);
    }
  }

  if (log) {
    console.log(
      `workie: ${generated.size} workflow(s) ` +
        `(${written.length} written, ${unchanged.length} unchanged, ${removed.length} removed)`,
    );
  }

  return { written, unchanged, removed };
}

/**
 * Derive a filename for the given task + package. Always starts with
 * `workie-`; the rest is a slug of the package path and task name.
 */
export function workflowFilename(task: string, pkg: PackageInfo): string {
  const slug = pkg.path.replace(/\//g, "-");
  return `${PREFIX}${slug}-${task}.yml`;
}
