import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { AFFECTED_STEP_ID, affected } from "./affected.ts";
import { collectSecrets, secretsToEnv } from "./secrets.ts";
import { taskRoots } from "./taskRoots.ts";
import {
  loadTurboGraph,
  type TurboGraph,
  transitiveDependencies,
} from "./turboGraph.ts";
import type {
  PackageInfo,
  TaskRoot,
  Workflow,
  WorkflowContext,
  WorkieConfig,
} from "./types.ts";
import { validateWorkflow } from "./validateWorkflow.ts";
import { yaml } from "./yaml.ts";

const PREFIX = "workie-";
const WORKFLOWS_DIR = ".github/workflows";
const HEADER = "# Auto-generated by workie -- do not edit manually.";

export type GenerateOptions = {
  /** Monorepo root. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Print a summary to stdout. Defaults to `true`. */
  log?: boolean;
  /**
   * Pre-computed turbo graph. If omitted, `generate` invokes `loadTurboGraph`
   * in `cwd`. Useful for tests.
   */
  graph?: TurboGraph;
};

export type GenerateResult = {
  /** Workflow filenames written or overwritten in this run. */
  written: string[];
  /** Workflow filenames that were up-to-date and left alone. */
  unchanged: string[];
  /** Stale `workie-*` workflow files deleted in this run. */
  removed: string[];
};

export async function generate(
  config: WorkieConfig,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  const cwd = options.cwd ?? process.cwd();
  const log = options.log ?? true;
  const absDir = join(cwd, WORKFLOWS_DIR);

  if (!existsSync(absDir) || !statSync(absDir).isDirectory()) {
    throw new Error(
      `workie: workflows directory not found: ${WORKFLOWS_DIR}\n` +
        `Create it first so workie knows it's writing to the right place.`,
    );
  }

  const graph = options.graph ?? loadTurboGraph(cwd);

  const written: string[] = [];
  const unchanged: string[] = [];
  const generated = new Map<string, string>();
  const errors: string[] = [];

  const allTasks = Object.keys(config.tasks);
  for (const [task, fn] of Object.entries(config.tasks)) {
    const otherTasks = allTasks.filter((t) => t !== task);
    const roots = taskRoots(graph, task, { otherTasks }).map((pkg) =>
      taskRoot(graph, pkg),
    );
    if (roots.length === 0) {
      continue;
    }
    const dependencies = sortPackages(
      new Set(roots.flatMap((r) => r.dependencies)),
    );
    const paths = [...new Set(roots.flatMap((r) => r.paths))].sort();
    const secrets = roots.flatMap((r) => collectSecrets(graph, r.pkg, task));
    const env = secretsToEnv([...new Set(secrets)].sort());
    const ctx: WorkflowContext = {
      task,
      roots,
      dependencies,
      paths,
      env,
      affected: affected(roots),
    };
    const workflow = fn(ctx);
    if (!workflow) {
      continue;
    }

    const result = validateWorkflow(workflow);
    const problems = result.ok ? workieProblems(workflow) : result.errors;
    if (problems.length > 0) {
      errors.push(
        `Task "${task}" produced an invalid workflow:\n  ` +
          problems.join("\n  "),
      );
      continue;
    }

    generated.set(workflowFilename(task), `${HEADER}\n\n${yaml(workflow)}`);
  }

  if (errors.length > 0) {
    throw new Error(`workie: ${errors.length} error(s)\n${errors.join("\n")}`);
  }

  mkdirSync(absDir, { recursive: true });

  for (const [filename, body] of generated) {
    const filepath = join(absDir, filename);
    if (existsSync(filepath) && readFileSync(filepath, "utf-8") === body) {
      unchanged.push(filename);
      continue;
    }
    writeFileSync(filepath, body);
    written.push(filename);
    if (log) {
      console.log(`  wrote ${join(WORKFLOWS_DIR, filename)}`);
    }
  }

  const removed: string[] = [];
  for (const entry of readdirSync(absDir)) {
    if (!entry.startsWith(PREFIX)) {
      continue;
    }
    if (!entry.endsWith(".yml") && !entry.endsWith(".yaml")) {
      continue;
    }
    if (generated.has(entry)) {
      continue;
    }
    unlinkSync(join(absDir, entry));
    removed.push(entry);
    if (log) {
      console.log(`  removed stale ${join(WORKFLOWS_DIR, entry)}`);
    }
  }

  if (log) {
    console.log(
      `workie: ${generated.size} workflow(s) ` +
        `(${written.length} written, ${unchanged.length} unchanged, ${removed.length} removed)`,
    );
  }

  return { written, unchanged, removed };
}

/** The filename of the workflow for `task`. Always starts with `workie-`. */
export function workflowFilename(task: string): string {
  return `${PREFIX}${task.replace(/\//g, "-")}.yml`;
}

function taskRoot(graph: TurboGraph, pkg: PackageInfo): TaskRoot {
  const dependencies = sortPackages(
    [...transitiveDependencies(graph, pkg.name)]
      .map((n) => graph.byName.get(n))
      .filter((p): p is PackageInfo => p !== undefined),
  );
  const paths = dependencies
    .map((p) => p.path)
    .filter((p) => p !== "")
    .map((p) => `${p}/**`)
    .sort();
  return { pkg, dependencies, paths };
}

function sortPackages(packages: Iterable<PackageInfo>): PackageInfo[] {
  return [...packages].sort((a, b) => a.path.localeCompare(b.path));
}

/** Checks the schema can't express: a manual trigger, and the affected step. */
function workieProblems(workflow: Workflow): string[] {
  const problems: string[] = [];
  const on = workflow.on;
  const manual =
    typeof on === "string"
      ? on === "workflow_dispatch"
      : Array.isArray(on)
        ? on.includes("workflow_dispatch")
        : "workflow_dispatch" in on;
  if (!manual) {
    problems.push(
      "/on needs a workflow_dispatch trigger, for running every package",
    );
  }
  for (const [id, job] of Object.entries(workflow.jobs)) {
    const usesOutputs = JSON.stringify(job).includes(
      `steps.${AFFECTED_STEP_ID}.outputs`,
    );
    const hasStep = (job.steps ?? []).some((s) => s.id === AFFECTED_STEP_ID);
    if (usesOutputs && !hasStep) {
      problems.push(
        `/jobs/${id} uses affected.filter or affected.if() without affected.step()`,
      );
    }
  }
  return problems;
}
