name: Rust
on:
  - pull_request
  - workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  utf64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - working-directory: ./utf64/rust
      run: cargo build --verbose
    - working-directory: ./utf64/rust
      run: cargo test --verbose
